- name: "{{ app_name }} create directory for .env files"
  file:
    path: "{{app_dir}}/{{ app_name }}"
    state: directory

- name: "{{ app.app_name }} create .env file"
  template:
    src: .env.template.j2
    dest: "{{app_dir}}/.env.{{app.app_name}}.{{ env }}"

- name: "{{ app_name }} Send service  file"
  template: src="systemd-unit.service" dest="/etc/systemd/system/{{ app_name }}.service"

- name: "{{ app_name }} Restart {{ app_name }} container"
  systemd:
    name: "{{ app_name }}.service"
    state: restarted
    daemon-reload: yes
    enabled: yes
