---
- hosts: localhost
  tasks:
    - debug:
        msg: "{{ lookup('file', key_file)}}"

- hosts: label_service_bdays
  become_user: root
  become: yes
  roles:
    - role: deploy-app
      tags:
        - app
        - deploy
