- hosts: localhost
  tasks:
    - name: Ensure .ssh directory exists.
      file:
        dest: "{{ key_file | dirname }}"
        mode: 0700
        owner: root
        state: directory

    - name: Install ssh key
      copy:
        content: "{{ ssh_key }}"
        dest: "{{ key_file }}"
        mode: 0600
        owner: root
