---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  when: nginx_load_default_vars
  tags: [always]

- include: selinux.yml
  when: ansible_selinux and ansible_selinux.status == "enabled"
  tags: [packages, selinux, nginx]

- include: nginx-official-repo.yml
  when: nginx_official_repo == True
  tags: [packages, nginx]

- include: installation.packages.yml
  when: nginx_installation_type == "packages"
  tags: [packages, nginx]

- include: ensure-dirs.yml
  tags: [configuration, nginx]

- include: modules.yml
  tags: [modules, nginx]

- include: remove-defaults.yml
  when: not nginx_keep_only_specified
  tags: [configuration, nginx]

- include: remove-extras.yml
  when: nginx_keep_only_specified
  tags: [configuration, nginx]

- include: remove-unwanted.yml
  tags: [configuration, nginx]

- include: configuration.yml
  tags: [configuration, nginx]

- include: cloudflare_configuration.yml
  when: nginx_set_real_ip_from_cloudflare == True
  tags: [configuration, nginx]

- name: Start the nginx service
  service: name={{ nginx_service_name }} state={{nginx_start_service | ternary('started', 'stopped')}} enabled={{nginx_start_at_boot}}
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"
  tags: [service, nginx]
