name: Publish Docker
on: [push]
    # branches:
    #   - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      uses: "actions/docker/cli@master"
      with:
        runs: "make"
        args: "build -t $GITHUB_REPOSITORY:$GITHUB_SHA ."
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${GITHUB_REPOSITORY}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  # deploy:
  #   name: deploy to host
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: deploy to cluster
  #     uses: steebchen/kubectl@master
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #     with:
  #       args: set image --record deployment/my-app container=${{ github.repository
  #         }}:${{ github.sha }}
  #   - name: verify deployment
  #     uses: steebchen/kubectl@master
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #     with:
  #       args: '"rollout status deployment/my-app"'
