name: Publish Docker
on: [push]
    # branches:
    #   - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and publishdocker image
      uses: "pangzineng/Github-Action-One-Click-Docker@master"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: add_key
      run: "echo ${VAULT_PASS}  > ./pass.vault"
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}
    - name: add_ssh_key
      uses: actions/docker/cli@master
      with:
        args: run --workdir /github/workspace --rm -v "/var/run/docker.sock":"/var/run/docker.sock" -v "secrets":"/temp/secrets" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/actions_probe/actions_probe":"/github/workspace" williamyeh/ansible:ubuntu14.04 ansible-playbook infrastructure/ansible/playbooks/sample/setup_key.yml -i infrastructure/ansible/environments/stage/static_hosts -e key_file=/temp/secrets/sample_id_rsa
    # - run: "cat /github/home/.ssh/sample_id_rsa"
    - name: deploy to stage
      uses: actions/docker/cli@master
      with:
        args: run --workdir /github/workspace --rm -v "/var/run/docker.sock":"/var/run/docker.sock"  -v "secrets":"/temp/secrets" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/actions_probe/actions_probe":"/github/workspace" williamyeh/ansible:ubuntu14.04 ansible-playbook infrastructure/ansible/playbooks/sample/deploy.yml -i infrastructure/ansible/environments/stage/static_hosts -e app_docker_image=$GITHUB_REPOSITORY -e app_docker_tag=${GITHUB_SHA:7} --private-key /temp/secrets/sample_id_rsa --user test
      # env:
      #   ACTION_PLAYBOOK_NAME:
      #     infrastructure/ansible/playbooks/sample/deploy.yml
