name: Publish Docker
on: [push]
    # branches:
    #   - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      uses: "actions/docker/cli@master"
      with:
        runs: "make"
        args: "build -t $GITHUB_REPOSITORY:$GITHUB_SHA ."
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chromko/actions_probe
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  staging_deploy:
    name: deploy to host
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to host
      uses: stoe/actions/ansible-playbook@master
      with:
        args: infrastructure/playbooks/sample/deploy.yml -i environments/stage/inventory.gcp.yml -e app_docker_image=$GITHUB_REPOSITORY -e app_docker_tag=$GITHUB_SHA
